import { index, integer, sqliteTable, text, unique } from 'drizzle-orm/sqlite-core'

// Phase 6 — session prescription. See
// docs/superpowers/specs/2026-09-08-training-plan-session-prescription-design.md
export const sessionTemplates = sqliteTable('session_templates', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  discipline: text('discipline', { enum: ['running', 'swimming', 'strength', 'cycling'] }).notNull(),
  targetIntensity: text('target_intensity', { enum: ['mobility', 'easy', 'moderate', 'hard'] }).notNull(),
  durationMinutes: integer('duration_minutes').notNull(),
  // 'any' matches regardless of the discipline's current periodization phase — most templates
  // (technique work, general easy sessions) aren't phase-specific; only build-only interval/
  // threshold work and deload-only easy sessions need a real value here.
  phase: text('phase', { enum: ['build', 'deload', 'any'] }).notNull().default('any'),
  structureJson: text('structure_json'), // flexible: intervals, sets/reps, etc.
  isArchived: integer('is_archived', { mode: 'boolean' }).notNull().default(false),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
})

export const loggedSessions = sqliteTable(
  'logged_sessions',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    date: text('date').notNull(),
    sessionTemplateId: integer('session_template_id').references(() => sessionTemplates.id),
    // Snapshot of what dayType.ts suggested at log time, so later changes to the derivation
    // rules never rewrite history for sessions already logged.
    plannedIntensityCeiling: text('planned_intensity_ceiling'),
    // 'planned' = generated by getDailyPrescription()/ensurePlannedSession(), not yet acted on.
    // Flipped to 'completed'/'skipped' by POST /api/training/log.
    status: text('status', { enum: ['planned', 'completed', 'skipped'] }).notNull().default('planned'),
    actualRpe: integer('actual_rpe'),
    actualDurationMinutes: integer('actual_duration_minutes'),
    notes: text('notes'),
    garminActivityId: text('garmin_activity_id'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  t => ({
    dateIdx: index('logged_sessions_date_idx').on(t.date),
    // Enforces "1 session per day max" (design doc decision) at the DB level, not just in
    // application logic — ensurePlannedSession()'s upsert relies on this constraint.
    dateUnique: unique('logged_sessions_date_unique').on(t.date),
  }),
)
